Codigo Fuente/web/views/conjuntos.py
from flask import request, session, Blueprint, render_template, redirect, send_file, url_for
from dotenv import load_dotenv
from datetime import datetime
from ast import literal_eval
from googletrans import Translator
import os, sys, json, pandas as pd

from services.db_cli import DB
from utils.modelo import preparar_data, verificar_data, ejecutar_modelo
from views.auth import login_required
from services.API import get, post, put, delete

from utils.utils import *

model_logger = logging.getLogger('model_logger')
error_logger = logging.getLogger('error_logger')

load_dotenv()

Conjunto = Blueprint('Conjunto', __name__)

endopoint = 'conjuntos/'

upload_folder = os.getcwd()+os.getenv("UPLOAD_FOLDER")

translator = Translator()

db = DB()

@Conjunto.route('/crudos')
@login_required
def crudos():
    return listar('crudos')

@Conjunto.route('/procesados')
@login_required
def procesados():
    return listar('procesados')
    
def listar(estado):
    status_p,body_p = get('programas')
    status_c,body_c = get('conjuntos/encargado/'+session['user']['correo']+'?estado='+estado)
    if status_c and status_p:
        return render_template(endopoint+estado+'.html', conjuntos=body_c, programas=body_p)        
    elif not(status_c) and not(status_p):
        error = {**body_c,**body_p}
    elif not(status_c):
        error = body_c
    else:
        error = body_p
    return render_template(endopoint+estado+'.html', conjuntos=[],error=error)

@Conjunto.route('/descargar/<estado>/<nombre>')
def descargar (estado, nombre):

    status_c,body_c = get('conjuntos/'+nombre)
    if not status_c:
        return render_template('utils/mensaje.html', mensaje='No existe ese conjunto')
    
    if estado.lower() == 'crudos':
        nombre = 'C '+nombre
    elif estado.lower() == 'procesados':
        nombre = 'P '+nombre
    else:
        return render_template('utils/mensaje.html', mensaje='Estado del conjunto incorrecto')

    ruta = upload_folder+'/'+estado.lower()+'/'+nombre
    
    if os.path.exists(ruta+'.xlsx'):
        return send_file(ruta+'.xlsx', as_attachment=True)
    elif os.path.exists(ruta+'.xls'):
        return send_file(ruta+'.xls', as_attachment=True)
    else:
        return render_template('utils/mensaje.html', mensaje='No se encontro el archivo a descargar')    
    

@Conjunto.route('/crear')
@login_required
def crear():
    status_f,body_f = get('facultades')
    status_p,body_p = get('programas')

    if status_f and status_p:
        return render_template(endopoint+'crear.html', facultades=body_f, programas=body_p)
    elif not(status_f) and not(status_p):
        error = {**body_f,**body_p}
    elif not(status_f):
        error = body_f
    else:
        error = body_p
    return render_template('utils/mensaje.html', mensaje='No se pudieron cargar las programas y las facultades', submensaje=error)

@Conjunto.route('/detalle',methods=['POST'])
@login_required
def detalle():
    # Obtener Lo valores del formulario
    body = dict(request.values)
    conjunto = literal_eval(body['conjunto'])
    # Consultas para mostrar info
    status_f,body_f = get('facultades')
    status_p,body_p = get('programas')
    status_u, body_u = get('usuarios')
    
    if status_p and status_f and status_u and conjunto:
        return render_template(endopoint+'detalle.html', facultades=body_f, programas=body_p, usuarios=body_u, c=conjunto)
    elif not(status_f) and not(status_p) and not(status_u):
        error = {**body_f,**body_p,**body_u}
    elif not(status_f):
        error = body_f
    elif not(status_p):
        error = body_p
    elif not(conjunto):
        return render_template('utils/mensaje.html', mensaje='No se encontro un conjunto para detallar')
    else:
        error = body_u
    return render_template('utils/mensaje.html', mensaje='No se pudieron cargar los datos para detallar el conjunto', submensaje=error)

@Conjunto.route('/crear', methods=['POST'])
@login_required
def guardar():
    # Obtener Lo valores del formulario
    conjunto = dict(request.values)
    # Preparar conjunto para la insercion
    del conjunto['facultad']
    conjunto['estado'] = 'Crudos'
    conjunto['periodoInicial'] = int(conjunto['periodoInicial'])
    conjunto['periodoFinal'] = int(conjunto['periodoFinal'])
    conjunto['programa'] = int(conjunto['programa'])
    conjunto['encargado'] = session['user']['correo']

    # Obtener nombre del conjunto desde el api
    status_n, body_n = post('conjuntos/nombre', conjunto)
    if status_n:
        nombre, numero = body_n['nombre'], body_n['numero']
    else:
        return render_template('utils/mensaje.html', mensaje='No se pudo obtener el nombre del conjunto', submensaje=body_n)

    archivo_guardar = 'C '+ nombre
    tipo = conjunto['tipo']
    ruta = upload_folder+'/crudos'
    archivo = request.files['archivo']

    # Guardar archivo en Upload folder

    ############# ARCHIVO ##############
    if (archivo.filename and tipo=='excel'):
        extension = '.'+archivo.filename.split('.')[1]
        # Guardar archivo de excel
        archivo_guardar = archivo_guardar + '.xls'
        if not (extension in ['.xls', '.xlsx']):
            return render_template('utils/mensaje.html', mensaje='Extension de archivo incorrecta: '+str(extension), submensaje='Solo se permiten archivos excel .xls & xlsx')
    
        # VERIFICACION de formato
        data = pd.read_excel(archivo)
        validacion, mensaje_error, data_verificada = verificar_data(data, conjunto['periodoInicial'], conjunto['periodoFinal'], conjunto['programa'])
        if validacion:
            try:
                data_verificada.to_excel(ruta+'/'+archivo_guardar, index=False)
                # archivo.save(os.path.join(ruta, nombre + extension))
            except Exception as e:
                error_logger.error(e)
                return render_template('utils/mensaje.html', mensaje='Ocurrio un error guardando el conjunto de datos')
        else:
            return render_template('utils/mensaje.html', mensaje='Incorrecto el formato de la fuente de datos', submensaje=mensaje_error)
    
    ############# CONSULTA ##############
    elif tipo=='consulta':
        # Obtener datos desde la bd SQL server       
        sql = "SELECT * FROM VWDATADESERCION WHERE idprograma={} AND registro >= {} AND registro <= {} "
        sentencia = sql.format(conjunto['programa'], conjunto['periodoInicial'], conjunto['periodoFinal'])
        data = db.select(sentencia)
        ex = exception(data)
        if ex: return ex
        
        # VERIFICACION de formato
        validacion, mensaje_error, data_verificada = verificar_data(data, conjunto['periodoInicial'], conjunto['periodoFinal'], conjunto['programa'])
        if validacion:
            # Guardar tabla sql como excel
            try:
                data_verificada.to_excel(ruta+'/'+archivo_guardar+'.xls', index=False)
            except Exception as e:
                error_logger.error(e)
                return render_template('utils/mensaje.html', mensaje='Ocurrio un error guardando el conjunto de datos')
        else:
            return render_template('utils/mensaje.html', mensaje='Incorrecto el formato de la fuente de datos', submensaje=mensaje_error)
    else:
        return render_template('utils/mensaje.html', mensaje='Formulario incorrecto', submensaje='Verifica el formulario de creacion o notifica al Administrador del sistema')
           
    # Guardar registro de conjunto en la BD
    conjunto['nombre'] =  nombre
    conjunto['numero'] =  numero
    status, body = post('conjuntos',conjunto)
    if status:
        return redirect(url_for('Conjunto.crudos'))
    else:
        return render_template('utils/mensaje.html', mensaje='No se pudo guardar el conjunto', submensaje=body)


@Conjunto.route('/preparar', methods=['POST'])
@login_required
def preparar():
    # Obtener Lo valores del formulario
    body = dict(request.values)
    conjunto = literal_eval(body['conjunto'])
    
    nombre = conjunto['nombre']

    # Actualizar conjunto de datos de crudo a en proceso 
    act_estado =  actualizar_estado(nombre,'En Proceso')
    if act_estado: return act_estado

    # Crear prepraracion
    preparacion = {}
    preparacion['conjunto'] = conjunto['nombre']
    preparacion['preparador'] = session['user']['correo']
    preparacion['fechaInicial'] = getNowDate()
    # Obtener numero de preparacion para el conjunto
    status_p, body_p = get('preparaciones/nombre/'+nombre)
    if status_p:
        preparacion['numero'] = body_p['numero']
        preparacion['nombre'] = body_p['nombre']
    else:
        return render_template('utils/mensaje.html', mensaje='No se pudo obtener el consecutivo de la preparacion para este conjunto', submensaje=body_p)

    ########### PREPARAR ############

    # Obtener archivo crudo
    archivo_crudo = 'C '+nombre 
    ruta = upload_folder+'/crudos/'+archivo_crudo
    exito,dataCruda = obtener_archivo_excel(ruta) 
    if not(exito): return dataCruda 

    # Algoritmo de preparacion
    try:
        dataPreparada = preparar_data(dataCruda)
    except Exception as e:
        model_logger.error(e)
        observaciones = {'error': str(e)}
        exito,pagina_error = guardar_preparacion(preparacion, observaciones,'Fallida')
        if not(exito): return pagina_error 
        return render_template('utils/mensaje.html', mensaje='La preparacion Fallo')

    # Guardar archivo en Upload folder procesados
    archivo_procesado = 'P '+nombre+'.xls'
    ruta = upload_folder+'/procesados/'+archivo_procesado
    exito,pagina_error = guardar_archivo(dataPreparada, ruta, 'excel')
    if not(exito): return pagina_error 

    # Guardar registro de preparacion en la BD 
    exito, pagina_error = guardar_preparacion(preparacion,None,'Exitosa')
    if not(exito): return pagina_error 

    ########### FIN PREPARAR ############    

    # Actualizar conjunto de datos de crudo a procesado
    act_estado =  actualizar_estado(nombre,'Procesados')

Codigo Fuente/web/views/resultados.py
from flask import request, session, Blueprint, render_template, redirect, send_file
from dotenv import load_dotenv
from ast import literal_eval
from datetime import datetime
import os, json, pandas as pd

from views.auth import login_required
from services.API import get, post, put, delete

from utils.utils import *

load_dotenv()

endopoint = 'resultados/'

Resultado = Blueprint('Resultado', __name__)

upload_folder = os.getcwd()+os.getenv("UPLOAD_FOLDER")

@Resultado.route('/preparaciones')
@Resultado.route('/preparaciones/<conjunto>')
@login_required
def preparaciones(conjunto=None):
    if conjunto:
        return listar_conjunto('preparaciones', conjunto)
    return listar('preparaciones')

@Resultado.route('/ejecuciones')
@Resultado.route('/ejecuciones/<conjunto>')
@login_required
def ejecuciones(conjunto=None):
    if conjunto:
        return listar_conjunto('ejecuciones',conjunto)
    return listar('ejecuciones')

def listar(resultados):
    rol = 'preparador' if resultados == 'preparaciones' else 'ejecutor'
    status, body = get(resultados+'/'+rol+'/'+session['user']['correo'])
    if status:
        return render_template(endopoint+resultados+'.html', resultados=set_date_format(body))
    else:
        return render_template(endopoint+resultados+'.html', resultados=[], error=body)

def listar_conjunto(resultados, conjunto):
    status, body = get(resultados+'/conjunto/'+conjunto)
    if status:
        return render_template(endopoint+resultados+'.html', resultados=set_date_format(body))
    else:
        return render_template(endopoint+resultados+'.html', resultados=[], error=body)


@Resultado.route('/ejecucion/detalle', methods=['POST'])
@login_required
def ejecucion_detalle():
    body = dict(request.values)
    ejecucion = body['ejecucion']

    # Obtener el archivo de desertores
    archivo = 'D '+ejecucion
    ruta = upload_folder+'/desertores/'+archivo
    exito,desertores = obtener_archivo_json(ruta)

    status, body = get('ejecuciones/'+ejecucion)
 
    if status and exito:
        del body['precision_modelo']
        del body['numero']
        return render_template(endopoint+'ejecucion_detalle.html', desertores=desertores, resultados=body.pop('resultados'), ejecucion=body )
    elif status and not(exito):
        if body['estado'] == 'Fallida':
            del body['precision_modelo']
            del body['numero']
            return render_template(endopoint+'ejecucion_detalle.html', desertores=None, resultados=body.pop('resultados'), ejecucion=body )
        else:
            return desertores
    else:
        return render_template('utils/mensaje.html', mensaje='No se obtener la ejecucion', submensaje=body)

@Resultado.route('/preparacion/detalle', methods=['POST'])
@login_required
def preparacion_detalle():
    body = dict(request.values)
    preparacion = body['preparacion']
    status, body = get('preparaciones/'+preparacion)
    
    if status:
        del body['numero']
        return render_template(endopoint+'preparacion_detalle.html', observaciones=body.pop('observaciones') ,p=body )
    else:
        return render_template('utils/mensaje.html', mensaje='No se obtener los resultaods de la ejecucion', submensaje=body)


@Resultado.route('/descargar/desertores/<ejecucion>', methods=['GET'])
@login_required
def descargar(ejecucion):
    status_c,body_c = get('ejecuciones/'+ejecucion)
    if not status_c:
        return render_template('utils/mensaje.html', mensaje='No existe esa ejecucion')

    archivo = 'D '+ejecucion
    ruta = upload_folder+'/desertores/'+archivo
    try:
        data = pd.read_json(ruta+'.json')
    except Exception as e:
        return render_template('utils/mensaje.html', mensaje='No se pudo abrir el archivo de desertores:', submensaje=str(e))
    
    exito,pagina_error = guardar_archivo(data,ruta+'.xls','excel')
    if not(exito): return pagina_error 

    return send_file(ruta+'.xls', as_attachment=True)

Codigo Fuente/web/templates/conjuntos/crudos.html
{% include 'components/header.html' %}

{% with menu='conjuntos' %}
    {% include 'components/sideBar.html' %}
{% endwith %}

<h4>Conjuntos de Datos</h4>
<br>

<!-- Input de filtrado -->
<div class="row ml-1 mt-2">
  &nbsp;<i class="fas fa-filter mr-2 mt-2"></i>&nbsp;
  <input type="text" class="form-control form-control-sm w-25" id="filtro_tabla" placeholder="Filtrar tabla...">
</div>
<br>

<!-- Tabs de navegacion -->
<ul class="nav nav-tabs mb-4">
  <li class="nav-item">
    <a class="nav-link active" href="#">Crudos</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-dark bg-light border" href="{{url_for('Conjunto.procesados')}}">Procesados</a>
  </li>
</ul>

<!-- Tabla -->
<div class="table-responsive-sm ">
  <table class="table table-hover table-sm" id="tabla">
    <thead>
      <tr class="border-top-0">
        <th scope="col" class="border-top-0">
          <center>Nombre</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Tipo</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Número</center>
        </th>

        <th scope="col" class="border-top-0">
          <center>Período Inicial</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Período Final</center>
        </th>
        <th scope="col" class="border-top-0">
          <center> Programa </center>
        </th>
        <th scope="col" class="border-top-0">
          <center> Acciones</center>
        </th>
      </tr>
    </thead>
    <tbody>

      {% for c in conjuntos %}
      <tr>
        <td>
          <center>{{ c.nombre }}</center>
        </td>
        <td>
          <center>{{ c.tipo }}</center>
        </td>
        <td>
          <center>{{ c.numero }}</center>
        </td>
        <td>
          <center>{{ c.periodoInicial }}</center>
        </td>
        <td>
          <center>{{ c.periodoFinal }}</center>
        </td>
        <td>
          {% for p in programas %}
          {% if c.programa==p.codigo %}
          <center>{{p.nombre}}</center>
          {% endif %}
          {% endfor %}
        </td>
        <td>
          <!-- ACCCIONES -->
          <div class="row d-flex justify-content-center">

            <!-- PREPARAR -->
            <form action="{{url_for('Conjunto.preparar')}}" method="POST">
              <input type="hidden" name="conjunto" value="{{c}}">
              <!-- Boton para preparar y de carga -->
              <input id="btn-submit" type="submit" data-toggle="tooltip" data-placement="bottom" title="Preparar"
                class="btn btn-outline-dark btn-sm submit" role="status" value="&#9881;">
              <button class="btn btn-outline-dark btn-sm btn-loading" type="button" style="display: none;">
                <i class="fas fa-spinner fa-spin fa-lg" aria-hidden="true"></i>
              </button>

            </form>

            &nbsp;

            <!-- VER DETALLE-->
            <form action="{{url_for('Conjunto.detalle')}}" method="POST">
              <input type="hidden" name="conjunto" value="{{c}}">
              <button type="submit" data-toggle="tooltip" data-placement="bottom" title="Ver Detalle"
                class="btn btn-outline-dark btn-sm submit" role="status">
                <i class="fas fa-search-plus"></i>
                </button>
            </form>

          </div>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

</div>

{% if error %}
<br>
{% with titulo='No se pudieron cargar los conjuntos',error=error %}
{% include "components/alert.html" %}
{% endwith %}
<br>
{% endif %}


{% with titulo='Preparando',tipo='preparacion',num='1000 registros',den='1.8 segundos' %}
{% include "components/modal.html" %}
{% endwith %}

<br>

<a href="{{url_for('Conjunto.crear') }}" type="button" class="btn btn-dark text-white my-primary mt-4">
  <i class="fas fa-file-upload mr-1"></i>
  Nuevo</a>

<script>
  // Cargando si se esta validando y guardando la data del conjunto 
  $('#btn-submit').click(function () {
    handleModal('Su conjunto aparecera cuando acabe el proceso', "{{url_for('Conjunto.procesados')}}")
  })
</script>

{% include 'components/footer.html' %}

Codigo Fuente/web/templates/conjuntos/detalle.html
{% include 'components/header.html' %}

{% with menu='conjuntos' %}
    {% include 'components/sideBar.html' %}
{% endwith %}

<h4>Detalle de un Conjunto de Datos</h4>
<br>

{% if c.nombre %}
<form class="jumbotron py-4 pr-2 bg-light" style="width:70%;">
    <div class="container">
        <div class="form-group row">
            <div class="col-sm-7">
                <label>Nombre</label>
                <input type="text" class="form-control" maxlength="30" value="{{c.nombre}}" disabled>

            </div>
            <div class="col-sm-4">
                <label>Estado de datos</label>
                <input type="text" class="form-control" maxlength="50" value="{{c.estado}}" disabled>
            </div>


        </div>

        <div class="form-group row">
            <div class="col-sm-11">
                <label>Programa</label>
                {% for p in programas %}
                {% if c.programa==p.codigo %}
                <input type="text" class="form-control" maxlength="30" value="{{p.nombre}}" disabled>
                {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-2">
                <label>Número</label>
                <input type="text" class="form-control" maxlength="6" value="{{c.numero}}" disabled>
            </div>
            <div class="col-sm-3">
                <label>Período Inicial</label>
                <input type="text" class="form-control" maxlength="6" value="{{c.periodoInicial}}" disabled>
            </div>
            <div class="col-sm-3">
                <label>Período Final</label>
                <input type="text" class="form-control" maxlength="6" value="{{c.periodoFinal}}" disabled>
            </div>
            <div class="col-sm-3 mr-0 pr-0">
                <label>Tipo</label>
                <br>
                <div class="container">
                    <div class="row">
                        <span class="mr-2" style="white-space: nowrap;">
                            {% if c.tipo=='consulta' %}
                            <input type="radio" name="tipo" checked disabled>
                            &nbsp;<small><b>Consulta</b></small>
                            {% else %}
                            <input type="radio" name="tipo" disabled>
                            &nbsp;<small>Consulta</small>
                            {% endif %}
                        </span>
                        <br>
                        <span>
                            {% if c.tipo=='excel' %}
                            <input type="radio" name="tipo" checked disabled>
                            &nbsp;<small><b>Excel</b></small>
                            {% else %}
                            <input type="radio" name="tipo" disabled>
                            &nbsp;<small>Excel</small>
                            {% endif %}
                        </span>
                    </div>
                </div>

            </div>


        </div>
        <div class="form-group row">
            <div class="col-sm-11">
                <label>Encargado</label>
                {% for u in usuarios %}
                {% if c.encargado==u.correo %}
                <input type="text" class="form-control" maxlength="30" value="{{u.nombre}}" disabled>
                {% endif %}
                {% endfor %}
                <br>
                <input type="text" class="form-control" maxlength="200" value="{{c.encargado}}" disabled>
            </div>
        </div>

        {% if c.estado=='Crudos' %}
        <br>
        <div class="form-group row ">
            <div class="col-sm-11 d-flex justify-content-center align-items-center">
                <i class="fa fa-download" aria-hidden="true"></i>
                &nbsp;
                <strong class="mr-2 d-flex ">Descargar: </strong>
                &nbsp;&nbsp;
                <a class="btn bg-white btn-sm border text-dark" type="button" href="{{url_for('Conjunto.descargar',estado='crudos',nombre=c.nombre)}}">
                    <i class="fas fa-file-excel mr-1"></i>
                    Crudo
                </a>
            </div>
        </div>
        {% endif %}

        {% if c.estado=='Procesados' %}

        <br>
        <div class="form-group row ">
            <div class="col-sm-6 d-flex justify-content-center">
                <!-- RESULTADOS -->
                <div class="dropdown dropdown-costum">
                    <button type="button" class="btn bg-white btn-sm border" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-list" aria-hidden="true"></i>
                        &nbsp;
                        <strong class="mr-2">Resultados</strong>
                        <i class="fas fa-caret-down"></i>
                    </button>
                    <div class="dropdown-menu r-menu border">

                        <!-- PREPARACIONES-->
                        <a class="dropdown-item" type="button" href="{{url_for('Resultado.preparaciones',conjunto=c.nombre)}}">
                            <small>&#9881;
                                Preparaciones</small>
                        </a>
                        <!-- EJECUCIONES-->
                        <a class="dropdown-item" type="button" href="{{url_for('Resultado.ejecuciones',conjunto=c.nombre)}}">
                            <small>&#9654;
                                Ejecuciones
                            </small>
                        </a>
                    </div>
                </div>
            </div>
            <div class="col-sm-6 ">
                <!-- DESCARGAS -->
                <div class="dropdown dropdown-costum ml-5">
                    <button type="button" class="btn bg-white btn-sm border" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-download" aria-hidden="true"></i>
                        &nbsp;
                        <strong class="mr-2">Descargar</strong>
                        <i class="fas fa-caret-down"></i>
                    </button>
                    <div class="dropdown-menu d-menu border">

                        <!-- ARCHIVO CRUDOS-->
                        <a class="dropdown-item w-100" type="button" href="{{url_for('Conjunto.descargar',estado='crudos',nombre=c.nombre)}}">
                            <small>
                                <i class="fas fa-file-excel mr-1"></i>
                                Crudo
                            </small>
                        </a>
                        <!-- ARCHIVO PROCESADOS-->
                        <a class="dropdown-item" type="button"  href="{{url_for('Conjunto.descargar', estado='procesados' ,nombre=c.nombre) }}">
                            <small><i class="fas fa-file-excel mr-1"></i>
                                Procesado
                            </small>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <script>
            $(document).ready(function ($) {
                $('.dropdown-costum').click(function () {
                    var dropdownMenu = $(this).children(".dropdown-menu");
                    if (dropdownMenu.is(":visible")) {
                        dropdownMenu.hide();
                    } else {
                        dropdownMenu.show();
                    }
                });
            })

        </script>
        <br>
        {% endif %}

        <br> 
        <div class="text-center ml-0 mr-5">
            <a class="btn btn-outline-dark ml-0 mr-3" onclick="window.history.go(-1)">Atras</a>
        </div>
</form>


{% else %}


<div class="alert alert-danger" role="alert">
    <h5 class="alert-heading">Aviso!!</h5>
    <p>No se pudo encontrar el Conjunto</p>
    <hr>
</div>

{% endif %}

{% include 'components/footer.html' %}

Codigo Fuente/web/templates/conjuntos/procesados.html
{% include 'components/header.html' %}

{% with menu='conjuntos' %}
    {% include 'components/sideBar.html' %}
{% endwith %}

<h4>Conjuntos de Datos</h4>
<br>

<!-- Input de filtrado -->
<div class="row ml-1 mt-2">
  &nbsp;<i class="fas fa-filter mr-2 mt-2""></i>&nbsp;
  <input type=" text" class="form-control form-control-sm w-25" id="filtro_tabla" placeholder="Filtrar tabla...">
</div>
<br>

<!-- Tabs de navegacion -->
<ul class="nav nav-tabs mb-4">
  <li class="nav-item">
    <a class="nav-link text-dark bg-light border" href="{{url_for('Conjunto.crudos')}}">Crudos</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="#">Procesados</a>
  </li>
</ul>

<!-- Tablas para listar -->
<div class="table-responsive-sm">
  <table class="table table-hover table-sm" id="tabla">
    <thead>
      <tr>
        <th scope="col" class="border-top-0">
          <center> Nombre </center>
        </th>
        <th scope="col" class="border-top-0">
          <center> Tipo </center>
        </th>
        <th scope="col" class="border-top-0">
          <center> Número </center>
        </th>
        <th scope="col" class="border-top-0">
          <center> Período Inicial </center>
        </th>
        <th scope="col" class="border-top-0">
          <center> Período Final </center>
        </th>
        <th scope="col" class="border-top-0">
          <center> Programa </center>
        </th>
        <th scope="col" class="border-top-0">
          <center> Acciones</center>
        </th>
      </tr>
    </thead>
    <tbody>
      {% for c in conjuntos %}
      <tr>
        <td>
          <center>{{ c.nombre }}</center>
        </td>
        <td>
          <center>{{ c.tipo }}</center>
        </td>
        <td>
          <center>{{ c.numero }}</center>
        </td>
        <td>
          <center>{{ c.periodoInicial }}</center>
        </td>
        <td>
          <center>{{ c.periodoFinal }}</center>
        </td>
        <td>
          {% for p in programas %}
          {% if c.programa==p.codigo %}
          <center>{{p.nombre}}</center>
          {% endif %}
          {% endfor %}
        </td>
        <td>
          <!-- ACCCIONES -->
          <div class="row d-flex justify-content-center">

            <!-- EJECUTAR -->
            <form action="{{url_for('Conjunto.ejecutar')}}" method="POST">
              <center>
                <input type="hidden" name="conjunto" value="{{c}}">
                <input id="btn-submit" type="submit" data-toggle="tooltip" data-placement="bottom" title="Ejecutar"
                  class="btn btn-outline-dark btn-sm submit" role="status" value="&#9654;">
                <button class="btn btn-outline-dark btn-sm btn-loading" type="button" style="display: none;">
                  <i class="fas fa-spinner fa-spin fa-lg" aria-hidden="true"></i>
                </button>
              </center>
            </form>
            &nbsp;

            <!-- VER DETALLE-->
            <form action="{{url_for('Conjunto.detalle')}}" method="POST">
              <input type="hidden" name="conjunto" value="{{c}}">
              <button type="submit" data-toggle="tooltip" data-placement="bottom" title="Ver Detalle"
                class="btn btn-outline-dark btn-sm submit" role="status">
                <i class="fas fa-search-plus"></i>
              </button>
            </form>
          </div>

        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<script>
  // Cargando si se esta validando y guardando la data del conjunto 
  $('#btn-submit').click(function () {
    handleModal('La ejecucion aparecera cuando acabe el proceso', "{{url_for('Resultado.ejecuciones')}}")
  })
</script>

<!-- Modal -->
{% with titulo='Ejecutando',tipo='ejecucion',num='1000 registros',den='20 segundos' %}
{% include "components/modal.html" %}
{% endwith %}

{% if error %}
<br>
{% with titulo='No se pudieron cargar los conjuntos',error=error %}
{% include "components/alert.html" %}
{% endwith %}
<br>
{% endif %}


<script>
  // Cargando si se esta validando y guardando la data del conjunto 
  $('#btn-submit').click(function () {
    handleModal('La ejecucion aparecera cuando acabe el proceso', "{{url_for('Resultado.ejecuciones')}}")
  })
</script>

{% include 'components/footer.html' %}