Codigo Fuente/web/views/auth.py
from flask import session, request, redirect, Blueprint, render_template
from functools import wraps
import os, dotenv, requests, jwt

dotenv.load_dotenv()

api = os.getenv("API_PATH")

Auth = Blueprint('auth', __name__)

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not 'user' in session.keys():
            return render_template('utils/login.html'), 200
        if session['user'] is None:
            return render_template('utils/login.html'), 200
        return f(*args, **kwargs)
    return decorated_function

def logout_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not 'user' in session.keys():
            return f(*args, **kwargs)
        if session['user'] is None:
            return f(*args, **kwargs)
        return render_template('utils/inicio.html'), 200
    return decorated_function

def only_admin(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not 'user' in session.keys():
            return render_template('utils/login.html'), 200
        if session['user'] is None:
            return render_template('utils/login.html'), 200
        if session['user']['rol']=='Admin':
            return f(*args, **kwargs)
        return render_template('utils/mensaje.html', mensaje="Usted no tiene autorizacion para realizar esta accion"), 401
    return decorated_function

@Auth.route('/login',methods=['GET','POST'])
@logout_required
def login():
    if request.method == 'GET':
        return render_template('utils/login.html'), 200

    # Loguear
    raw_usuario = dict(request.values)
    usuario = { 'correo': raw_usuario['InputEmailLogin'], 'clave': raw_usuario['InputPasswordLogin']}
    res = requests.post(api+'auth/login',json=usuario)
    status,body = res.status_code, res.json()
    if status==200:
        session['user'] = None
        session['headers'] = None
        # Obtener token
        token = body['access_token']
        # Setear usuario de la session
        user = jwt.decode(token,os.getenv('JWT_KEY'))['identity']
        session['user'] = user
        # Definir objeto request para realizar peticiones  al API 
        session['headers'] = {'Authorization': 'Bearer ' + token}        
        session.permanent = True

        return render_template('utils/inicio.html'), 200
    if 'msg' in body.keys():
        return render_template('utils/login.html',mensaje=body['msg']), 401
    return render_template('utils/error.html', mensaje="Ocurrió un error iniciando sesión", submensaje=body['error']), 400
    
    
@Auth.route('/logout')
@login_required
def logout():
    session['user'] = None
    session['headers'] = None
    session.clear()
    return render_template('utils/login.html'), 200

Codigo Fuente/web/views/resultados.py
from flask import request, session, Blueprint, render_template, redirect, send_file
from dotenv import load_dotenv
from ast import literal_eval
from datetime import datetime
import os, json, pandas as pd

from views.auth import login_required
from services.API import get, post, put, delete

from utils.utils import *

load_dotenv()

endopoint = 'resultados/'

Resultado = Blueprint('Resultado', __name__)

upload_folder = os.getcwd()+os.getenv("UPLOAD_FOLDER")

@Resultado.route('/preparaciones')
@Resultado.route('/preparaciones/<conjunto>')
@login_required
def preparaciones(conjunto=None):
    if conjunto:
        return listar_conjunto('preparaciones', conjunto)
    return listar('preparaciones')

@Resultado.route('/ejecuciones')
@Resultado.route('/ejecuciones/<conjunto>')
@login_required
def ejecuciones(conjunto=None):
    if conjunto:
        return listar_conjunto('ejecuciones',conjunto)
    return listar('ejecuciones')

def listar(resultados):
    rol = 'preparador' if resultados == 'preparaciones' else 'ejecutor'
    status, body = get(resultados+'/'+rol+'/'+session['user']['correo'])
    if status:
        return render_template(endopoint+resultados+'.html', resultados=set_date_format(body))
    else:
        return render_template(endopoint+resultados+'.html', resultados=[], error=body)

def listar_conjunto(resultados, conjunto):
    status, body = get(resultados+'/conjunto/'+conjunto)
    if status:
        return render_template(endopoint+resultados+'.html', resultados=set_date_format(body))
    else:
        return render_template(endopoint+resultados+'.html', resultados=[], error=body)


@Resultado.route('/ejecucion/detalle', methods=['POST'])
@login_required
def ejecucion_detalle():
    body = dict(request.values)
    ejecucion = body['ejecucion']

    # Obtener el archivo de desertores
    archivo = 'D '+ejecucion
    ruta = upload_folder+'/desertores/'+archivo
    exito,desertores = obtener_archivo_json(ruta)

    status, body = get('ejecuciones/'+ejecucion)
 
    if status and exito:
        del body['precision_modelo']
        del body['numero']
        return render_template(endopoint+'ejecucion_detalle.html', desertores=desertores, resultados=body.pop('resultados'), ejecucion=body )
    elif status and not(exito):
        if body['estado'] == 'Fallida':
            del body['precision_modelo']
            del body['numero']
            return render_template(endopoint+'ejecucion_detalle.html', desertores=None, resultados=body.pop('resultados'), ejecucion=body )
        else:
            return desertores
    else:
        return render_template('utils/mensaje.html', mensaje='No se obtener la ejecucion', submensaje=body)

@Resultado.route('/preparacion/detalle', methods=['POST'])
@login_required
def preparacion_detalle():
    body = dict(request.values)
    preparacion = body['preparacion']
    status, body = get('preparaciones/'+preparacion)
    
    if status:
        del body['numero']
        return render_template(endopoint+'preparacion_detalle.html', observaciones=body.pop('observaciones') ,p=body )
    else:
        return render_template('utils/mensaje.html', mensaje='No se obtener los resultaods de la ejecucion', submensaje=body)


@Resultado.route('/descargar/desertores/<ejecucion>', methods=['GET'])
@login_required
def descargar(ejecucion):
    status_c,body_c = get('ejecuciones/'+ejecucion)
    if not status_c:
        return render_template('utils/mensaje.html', mensaje='No existe esa ejecucion')

    archivo = 'D '+ejecucion
    ruta = upload_folder+'/desertores/'+archivo
    try:
        data = pd.read_json(ruta+'.json')
    except Exception as e:
        return render_template('utils/mensaje.html', mensaje='No se pudo abrir el archivo de desertores:', submensaje=str(e))
    
    exito,pagina_error = guardar_archivo(data,ruta+'.xls','excel')
    if not(exito): return pagina_error 

    return send_file(ruta+'.xls', as_attachment=True)

Codigo Fuente/web/views/tableros.py
from flask import request, session, Blueprint, render_template, redirect, send_file, jsonify
import plotly
import json
import numpy as np
import os

from views.auth import login_required

# Importar tableros de plotly para cada nivel
import utils.tableros.mundo as Mundo
import utils.tableros.pais as Pais
import utils.tableros.region as Region
import utils.tableros.ies as IES
import utils.tableros.programa as Programa
import utils.tableros.estudiante as Estudiante_file
from utils.tableros.estudiante import Estudiante

endopoint = 'tableros/'

Tablero = Blueprint('Tablero', __name__)

niveles = [
    {'nombre': 'Nivel Mundo', 'ruta': '/mundo'},
    {'nombre': 'Nivel Pais', 'ruta': '/pais'},
    {'nombre': 'Nivel Region', 'ruta': '/region'},
    {'nombre': 'Nivel IES', 'ruta': '/institucion'},
    {'nombre': 'Nivel Programa', 'ruta': '/programa'},
    {'nombre': 'Nivel Estudiante', 'ruta': '/estudiante'},
]
periodos = np.arange(2010, 2019, 1)


@Tablero.route('/')
def menu():
    return render_template(endopoint+'index.html', niveles=niveles)


def to_plotly_json(fig):
    plt = json.dumps(fig, cls=plotly.utils.PlotlyJSONEncoder)
    return plt

############################################################## NIVEL MUNDO ################################################################
@Tablero.route('/mundo')
@login_required
def mundo_dashboard():
    # Series Por pais
    pais = request.args.get('pais')

    if pais:
        gastos, inscripciones = Mundo.series_pais(pais)
        gastos, inscripciones = to_plotly_json(
            gastos), to_plotly_json(inscripciones)
        return jsonify([gastos, inscripciones])
    else:
        gastos, inscripciones = Mundo.series_pais('COL')

    clusters = to_plotly_json(Mundo.clusters())
    mapa = to_plotly_json(Mundo.mapa())
    gastos, inscripciones = to_plotly_json(
        gastos), to_plotly_json(inscripciones)

    return render_template(
        endopoint+'mundial.html',
        gastos_plot=gastos,
        inscrp_plot=inscripciones,
        mapa_plot=mapa,
        clusters_plot=clusters
    )

############################################################## NIVEL PAIS ################################################################
@Tablero.route('/pais')
@login_required
def pais_dashboard():
    # Series Por pais
    periodo = request.args.get('periodo')
    if not periodo:
        periodo = '2018'

    mapa = to_plotly_json(Pais.mapa(periodo))
    barras = to_plotly_json(Pais.barras())
    pastel = to_plotly_json(Pais.pastel(periodo))
    genero = to_plotly_json(Pais.genero(periodo))
    indicadores = to_plotly_json(Pais.indicadores(periodo))
    indicadores2 = to_plotly_json(Pais.indicadores2(periodo))

    return render_template(
        endopoint+'nacional.html',
        mapa_plot=mapa,
        barras_plot=barras,
        pastel_plot=pastel,
        genero_plot=genero,
        indicadores_plot=indicadores,
        indicadores2_plot=indicadores2,
        periodos_list=periodos,
        periodo=int(periodo),
    )


############################################################## NIVEL REGION ################################################################
@Tablero.route('/region')
@login_required
def region_dashboard():

    periodo = request.args.get('periodo')
    dpto = request.args.get('dpto')

    if not periodo:
        periodo = '2018'
    if not dpto:
        dpto = 'ANTIOQUIA'

    dptos = Region.dptos

    # Mapa dpto
    mapa = Region.mapa(dpto, periodo)
    mapa = to_plotly_json(mapa) if mapa else None

    # Barras verticales retencion
    barras = Region.barras(dpto)
    barras = to_plotly_json(barras)if barras else None

    # Pastel sector IES matricula
    pastel = Region.pastel(dpto, periodo)
    pastel = to_plotly_json(pastel) if pastel else None

    # Barras genero matricula
    genero = Region.genero(dpto, periodo)
    genero = to_plotly_json(genero) if genero else None

    # Indicadores departamento
    indicadores_dpto = Region.indicadores_dpto(dpto, periodo)
    indicadores_dpto = to_plotly_json(
        indicadores_dpto) if indicadores_dpto else None

    # Indicadores y miniserie matricula
    indicadores_ies, cant_ies = Region.indicadores_ies(dpto)
    indicadores_ies = to_plotly_json(
        indicadores_ies) if indicadores_ies else None

    # Barras horizontales desercion (Solo Antioquia)
    barras_ies = Region.barras_ies(dpto, periodo)
    barras_ies = to_plotly_json(barras_ies) if barras_ies else None

    if cant_ies:
        if cant_ies < 10:
            ies_size = cant_ies*5*10
        else:
            ies_size = cant_ies*1.7*10
    else:
        ies_size = 0

    return render_template(
        endopoint+'regional.html',
        periodo=int(periodo),
        dpto=str(dpto),

        periodos_list=periodos,
        dptos_list=dptos,
        ies_size=ies_size,

        mapa_plot=mapa,
        barras_plot=barras,
        pastel_plot=pastel,
        genero_plot=genero,

        indicadores_dpto_plot=indicadores_dpto,
        indicadores_ies_plot=indicadores_ies,

        barras_ies_plot=barras_ies,
    )
############################################################## NIVEL IES ################################################################
@Tablero.route('/institucion')
@login_required
def ies_dashboard():
    periodo = request.args.get('periodo')

    if not periodo:
        periodo = '20192'

    periodos = IES.periodos

    # Indicadores IES
    indicadores1 = IES.indicadores1(periodo)
    indicadores1 = to_plotly_json(indicadores1) if indicadores1 else None

    indicadores2 = IES.indicadores2(periodo)
    indicadores2 = to_plotly_json(indicadores2) if indicadores2 else None

    # Barras facultades
    barras = IES.barras(periodo)
    barras = to_plotly_json(barras) if barras else None

    # Pastel facultades
    pastel = IES.pastel(periodo)
    pastel = to_plotly_json(pastel) if pastel else None

    # Lista Indicadores Programas
    indicadores_programas, cant_prgms_1 = IES.indicadores_programas(periodo)
    indicadores_programas = to_plotly_json(
        indicadores_programas) if indicadores_programas else None
    if cant_prgms_1:
        if cant_prgms_1 < 10:
            prgms_size_1 = cant_prgms_1*5*10
        else:
            prgms_size_1 = cant_prgms_1*1.7*10
    else:
        prgms_size_1 = 0

    # Lista Mini serie Programas
    miniseries_programas, cant_prgms_2 = IES.miniseries_programas()
    miniseries_programas = to_plotly_json(
        miniseries_programas) if miniseries_programas else None
    if cant_prgms_2:
        if cant_prgms_2 < 10:
            prgms_size_2 = cant_prgms_2*5*10
        else:
            prgms_size_2 = cant_prgms_2*1.7*10
    else:
        prgms_size_2 = 0

    return render_template(
        endopoint+'institucional.html',
        periodo=int(periodo),

        periodos_list=periodos,

        nombre_ies=os.getenv('CLI_IES_NAME'),

        prgms_size_1=prgms_size_1,
        prgms_size_2=prgms_size_2,

        indicadores_1_plot=indicadores1,
        indicadores_2_plot=indicadores2,

        barras_plot=barras,

        pastel_plot=pastel,

        indicadores_programas_plot=indicadores_programas,
        miniseries_programas_plot=miniseries_programas
    )

############################################################## NIVEL PROGRAMA ################################################################
@Tablero.route('/programa')
@login_required
def programa_dashboard():
    periodo = request.args.get('periodo')
    programa = request.args.get('programa')

    if not periodo:
        periodo = '20192'
    if not programa:
        programa = 'INGENIERÍA CIVIL'

    periodos = Programa.periodos
    programas = Programa.programas

    # Indicadores Programa
    indicadores = Programa.indicadores(periodo, programa)
    indicadores = to_plotly_json(indicadores) if indicadores else None

    # Radial Matricula
    radial = Programa.radial(programa)
    radial = to_plotly_json(radial) if radial else None

    # Pastel Estratos
    pastel = Programa.pastel(programa)
    pastel = to_plotly_json(pastel) if pastel else None

    # Barras Desertores
    barras = Programa.barras(programa)
    barras = to_plotly_json(barras) if barras else None

    return render_template(
        endopoint+'programa.html',
        periodo=int(periodo),
        programa=programa,
        # TODO diferencia el codigo del programa y el nombre
        nombre_programa=programa,
        nombre_ies=os.getenv('CLI_IES_NAME'),
        periodos_list=periodos,
        programas_list=programas,

        indicadores_plot=indicadores,
        radial_plot=radial,
        pastel_plot=pastel,
        barras_plot=barras,
    )


############################################################## NIVEL ESTUDIANTE ################################################################
@Tablero.route('/estudiante')
@login_required
def estudiante_dashboard():
    periodos = Estudiante_file.periodos
    programas = Estudiante_file.programas

    programa = request.args.get('programa')
    periodo = request.args.get('periodo')
    documento = request.args.get('documento')

    try:
        periodo = int(periodo)
    except Exception as e:
        periodo = None

    # Obtener la lista de estudiantes de un programa
    if programa and not documento:
        estudiantes_programa = Estudiante_file.estudiantes_programa(programa)
        return render_template(
            endopoint+'estudiantes_programa.html',
            estudiantes_list=estudiantes_programa,
            programa=programa,
            programas_list=programas,
        )
    
    # Buscar estudiante por programa o cedula
    if not documento:
        return render_template(
            endopoint+'buscar_estudiante.html',
            periodos_list=periodos,
            programas_list=programas,
        )

    # Obtener los graficos del estudiantes por documento identificacion
    estudiante = Estudiante(identificacion=documento,

Codigo Fuente/web/templates/components/alert.html
<div class="alert alert-warning mb-0 pb-0" style="display: inline-block;" role="alert">
    <strong>{{titulo}}</strong>
    {% for key, value in error.items() %}
    <p>{{ value }} </p>
    {% endfor %}
</div>

Codigo Fuente/web/templates/components/footer.html
<!-- container -->
</div>

</div>
<!-- Main Col END -->

</div>
<!-- body-row END -->

</body>
<!-- 
<footer class="page-footer font-small" style="background-color: #0e1f3b; width: 100% ;height: 50%; position: absolute;">
    <div class="footer-copyright text-center py-3">© 2020 Copyright:
        <a href="https://mdbootstrap.com/"> pleyades.com</a>
    </div>
</footer> 
-->

<!-- Frameworks js -->


<!-- Coustum js -->
<script text="text/javascript" src="{{url_for('static', filename='dist/js/main.js') }}"></script>

</html>

Codigo Fuente/web/templates/components/modal.html
<!-- Modal -->
<div id="myModal" class="modal fade p-5" role="dialog" aria-hidden="true" data-backdrop="static" data-keyboard="false">
  <div class="modal-dialog modal-dialog-centered modal-sm w-15">
    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-body">
        <center>
          <h3 class="modal-title">{{titulo}}...</h3>
          <br>
          <p>Por favor espere a que el proceso termine
            <!-- <br>Tasa de tiempo {{tipo}}:<br>
            <sup>{{num}}</sup> &#8260; <sub>{{den}}</sub> -->
          </p>
          <br>
          <i class="fas fa-circle-notch fa-spin fa-4x mb-3"></i>
          <br>
        </center>
      </div>
    </div>
  </div>
</div>
<script>$('#myModal').modal('hide');</script>

Codigo Fuente/web/templates/components/sideBar.html
<!-- Bootstrap row -->
<div class="container-fluid p-0">
    <div class="row" id="body-row">

        <!-- Sidebar -->
        {% if session['user'] %}
        <div id="sidebar-container" class="sidebar border-right my-secondary"">
            <!-- d-* hiddens the Sidebar in smaller devices. Its itens can be kept on the Navbar 'Menu' -->
            <!-- Bootstrap List Group -->
       


                <ul class=" list-group mt-3 " style=" height: 100%;" style="margin-bottom:0px;">
            <!-- Opciones -->
            <li
                class="list-group-item sidebar-separator-title text-white d-flex align-items-center menu-collapsed border-right-0 border-left-0  my-secondary">
                <small>OPCIONES</small>

            </li>

            <!-- CONJUNTOS MENU -->
            <a href="#menuConjuntos" data-toggle="collapse" aria-expanded="false"
                class="list-group-item  flex-column align-items-start my-secondary border-top">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="fa fa-database fa-fw mr-3 text-white"></span>
                    <span class="menu-collapsed text-white">Conjuntos de Datos</span>
                    <span class="submenu-icon ml-auto"></span>
                </div>
            </a>
            <!-- Submenu content -->
            <div {% if menu=='conjuntos' %} style="display:inline;" {% endif %} id='menuConjuntos'
                class="sidebar-submenu collapse">
                <a href="{{url_for('Conjunto.crudos')}}"
                    class="list-group-item  text-white  border-right-0 my-secondary">
                    &#8226;&nbsp;&nbsp;<span class="menu-collapsed text-white">Crudos</span>
                </a>
                <a href="{{url_for('Conjunto.procesados')}}"
                    class="list-group-item  text-white border-right-0 my-secondary">
                    &#8226;&nbsp;&nbsp;<span class="menu-collapsed text-white">Procesados</span>
                </a>
            </div>
            <!-- RESULTADOS MENU -->
            <a href="#menuResultados" data-toggle="collapse" aria-expanded="false"
                class="list-group-item  flex-column align-items-start  border-right-0 my-secondary">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <i class="fa fa-list fa-fw mr-3 text-white" aria-hidden="true"></i>
                    <span class="menu-collapsed text-white">Resultados</span>
                    <span class="submenu-icon ml-auto"></span>
                </div>
            </a>
            <div {% if menu=='resultados' %} style="display:inline;" {% endif %} id='menuResultados'
                class="sidebar-submenu collapse">
                <a href="{{url_for('Resultado.preparaciones')}}"
                    class="list-group-item  text-white  border-right-0 my-secondary">
                    &#8226;&nbsp;&nbsp;<span class="menu-collapsed text-white">Preparaciones</span>
                </a>
                <a href="{{url_for('Resultado.ejecuciones')}}"
                    class="list-group-item  text-white border-right-0 my-secondary">
                    &#8226;&nbsp;&nbsp;<span class="menu-collapsed text-white">Ejecuciones</span>
                </a>
            </div>
            <!-- TABLEROS MENU -->
            <a href="#menuTableros" data-toggle="collapse" aria-expanded="false"
                class="list-group-item  flex-column align-items-start border-right-0 my-secondary">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="fa fa-chart-bar fa-fw mr-3 text-white" aria-hidden="true"></span>

                    <span class="menu-collapsed text-white">Tableros</span>
                    <span class="submenu-icon ml-auto"></span>
                </div>
            </a>
            <div {% if menu=='tableros' %} style="display:inline;" {% endif %} id='menuTableros'
                class="sidebar-submenu collapse">
                <a href="{{url_for('Tablero.mundo_dashboard')}}" class="list-group-item  text-white  border-right-0 my-secondary">
                    &nbsp;&nbsp;<i class="fa fa-globe-americas fa-xs" aria-hidden="true"></i>
                    <span class="menu-collapsed text-white">Mundo</span>
                </a>
                <a href="{{url_for('Tablero.pais_dashboard')}}" class="list-group-item  text-white border-right-0 my-secondary">
                    &nbsp;&nbsp;<i class="fa fa-flag fa-xs" aria-hidden="true"></i>
                    <span class="menu-collapsed text-white">País</span>
                </a>
                <a href="{{url_for('Tablero.region_dashboard')}}" class="list-group-item  text-white border-right-0 my-secondary">
                    &nbsp;&nbsp;<i class="fa fa-mountain fa-xs" aria-hidden="true"></i>
                    <span class="menu-collapsed text-white">Región</span>
                </a>
                <a href="{{url_for('Tablero.ies_dashboard')}}" class="list-group-item  text-white border-right-0 my-secondary">
                    &nbsp;&nbsp;<i class="fa fa-school fa-xs" aria-hidden="true"></i>
                    <span class="menu-collapsed text-white">IES</span>
                </a>
                <a href="{{url_for('Tablero.programa_dashboard')}}" class="list-group-item  text-white border-right-0 my-secondary">
                    &nbsp;&nbsp;<i class="fa fa-graduation-cap fa-xs" aria-hidden="true"></i>
                    <span class="menu-collapsed text-white">Programa</span>
                </a>
                <a href="{{url_for('Tablero.estudiante_dashboard')}}" class="list-group-item  text-white border-right-0 my-secondary">
                    &nbsp;&nbsp;<i class="fa fa-user-graduate fa-xs" aria-hidden="true"></i>
                    <span class="menu-collapsed text-white">Estudiante</span>
                </a>
            </div>
            <!-- END Opciones -->

            <!--  Entidades -->
            {% if session['user']['rol']=='Admin' %}
            <li
                class="list-group-item sidebar-separator-title text-white d-flex align-items-center menu-collapsed text-white  border-right-0 border-left-0  mt-5 my-secondary ">
                <small>ENTIDADES</small>
            </li>
            <a href="{{url_for('Facultad.listar')}}" class="list-group-item  border-right-0 border-top my-secondary">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="fa fa-university fa-fw mr-3 text-white"></span>
                    <span class="menu-collapsed text-white">Facultades</span>
                </div>
            </a>
            <a href="{{url_for('Programa.listar')}}" class="list-group-item  my-secondary">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="fa fa-graduation-cap fa-fw mr-3 text-white"></span>
                    <span class="menu-collapsed text-white">Programas</span>
                </div>
            </a>
            <a href="{{url_for('Usuario.listar')}}" class="list-group-item  border-right-0 my-secondary light">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="fa fa-user fa-fw mr-3 light"></span>
                    <span class="menu-collapsed light">Usuarios</span>
                </div>
            </a>
            <a href="{{url_for('ConjuntoAdmin.crudos')}}" class="list-group-item  border-right-0 my-secondary light">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <span class="fa fa-database fa-fw mr-3 text-white"></span>
                    <span class="menu-collapsed light">Conjuntos</span>
                </div>
            </a>
            <a href="{{url_for('ResultadoAdmin.preparaciones')}}"
                class="list-group-item  border-right-0 my-secondary light">
                <div class="d-flex w-100 justify-content-start align-items-center">
                    <i class="fa fa-list fa-fw mr-3 text-white" aria-hidden="true"></i>
                    <span class="menu-collapsed light">Resultados</span>
                </div>
            </a>
            {% endif %}
            <!-- END Entidades -->

            <!-- COLLAPSE Button -->
            <a href="#" data-toggle="sidebar-colapse"
                class="list-group-item align-items-center border border-right-0 my-secondary align-bottom"
                style="margin-top: auto; margin-left: -0.8px; margin-bottom:0px;">
                <div class="mt-0 d-flex w-100 justify-content-start align-items-center">
                    <center>
                        <span id="collapse-icon" class="fa fa-2x mr-3 text-white"></span>
                    </center>
                    <!-- <span id="collapse-text" class="menu-collapsed text-white">Collapse</span> -->
                </div>
            </a>
            </ul>
            <!-- List Group END-->
        </div>
        {% endif %}
        <!-- sidebar-container END -->


        <!-- MAIN -->
        <div class="col m-4 px-3 py-2 ">