Codigo Fuente/web/views/auth.py
from flask import session, request, redirect, Blueprint, render_template
from functools import wraps
import os, dotenv, requests, jwt

dotenv.load_dotenv()

api = os.getenv("API_PATH")

Auth = Blueprint('auth', __name__)

def login_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not 'user' in session.keys():
            return render_template('utils/login.html'), 200
        if session['user'] is None:
            return render_template('utils/login.html'), 200
        return f(*args, **kwargs)
    return decorated_function

def logout_required(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not 'user' in session.keys():
            return f(*args, **kwargs)
        if session['user'] is None:
            return f(*args, **kwargs)
        return render_template('utils/inicio.html'), 200
    return decorated_function

def only_admin(f):
    @wraps(f)
    def decorated_function(*args, **kwargs):
        if not 'user' in session.keys():
            return render_template('utils/login.html'), 200
        if session['user'] is None:
            return render_template('utils/login.html'), 200
        if session['user']['rol']=='Admin':
            return f(*args, **kwargs)
        return render_template('utils/mensaje.html', mensaje="Usted no tiene autorizacion para realizar esta accion"), 401
    return decorated_function

@Auth.route('/login',methods=['GET','POST'])
@logout_required
def login():
    if request.method == 'GET':
        return render_template('utils/login.html'), 200

    # Loguear
    raw_usuario = dict(request.values)
    usuario = { 'correo': raw_usuario['InputEmailLogin'], 'clave': raw_usuario['InputPasswordLogin']}
    res = requests.post(api+'auth/login',json=usuario)
    status,body = res.status_code, res.json()
    if status==200:
        session['user'] = None
        session['headers'] = None
        # Obtener token
        token = body['access_token']
        # Setear usuario de la session
        user = jwt.decode(token,os.getenv('JWT_KEY'))['identity']
        session['user'] = user
        # Definir objeto request para realizar peticiones  al API 
        session['headers'] = {'Authorization': 'Bearer ' + token}        
        session.permanent = True

        return render_template('utils/inicio.html'), 200
    if 'msg' in body.keys():
        return render_template('utils/login.html',mensaje=body['msg']), 401
    return render_template('utils/error.html', mensaje="Ocurrió un error iniciando sesión", submensaje=body['error']), 400
    
    
@Auth.route('/logout')
@login_required
def logout():
    session['user'] = None
    session['headers'] = None
    session.clear()
    return render_template('utils/login.html'), 200

Codigo Fuente/web/views/errors.py
from flask import Blueprint, render_template, app
import logging
import os

error_logger = logging.getLogger('error_logger')

Error = Blueprint('error', __name__)
error_template = 'utils/error.html'

@Error.app_errorhandler(404)
def page_not_found(e):
    return render_template(error_template, error=str(e)), 404

@Error.app_errorhandler(405)
def method_not_allow(e):
    return render_template(error_template, error=str(e)), 405

@Error.app_errorhandler(500)
def handle_500(e):
    error_logger.error(e)
    return render_template(error_template,error=str(e)), 500

@Error.app_errorhandler(Exception)
def handle_exception(e):
    error_logger.error('EXCEPTION: '+str(e), exc_info=True)
    return render_template(error_template, exception=True), 500

Codigo Fuente/web/templates/utils/acerca.html
{% include 'components/header.html' %}
<center>
  <div class="bg-light m-5 p-5" style="max-width: 1000px;">

    <h2> <strong> Acerca del Proyecto</strong> </h2>

    <br><br><br>
    
    <div class="mx-5 px-5 lead text-justify " style="font-size: 15px;">
      Integrantes del proyecto:
      <br>
      <table class="mx-5">
        <tr>
          <td> &#8226; &nbsp; Walter Saul Alvarez </td>
          <td>&nbsp; &nbsp; <i class="fas fa-user-tie"></i></td>
          <td> &nbsp; &nbsp; Gerente del proyecto</td>
          
        </tr>
        <tr>
          <td> &#8226; &nbsp; Juan Bernando Quintero </td>
          <td> &nbsp; &nbsp; <i class="fas fa-robot"></i></td>
          <td> &nbsp; &nbsp; Experto en IA</td>
          
          <td></td>
        </tr>
        <tr>
          <td> &#8226; &nbsp; Melissa Parra Obando </td>
          <td>&nbsp; &nbsp; <i class="fas fa-chart-pie"></i></td>
          <td> &nbsp; &nbsp; Experta en Deserción</td>
          
        </tr>
        <tr>
          <td> &#8226; &nbsp; Juan Esteban Quintero </td>
          <td>&nbsp; &nbsp; <i class="fas fa-laptop-code"></i></td>
          <td> &nbsp; &nbsp; Dersarrollador</td>
          

        </tr>
      </table>

      <br><br>

      Surgimiento del nombre:
      <br>
      <div class="mx-5">
        Astronomía
        <br>
        Las Pléyades o Las siete hermanas es un cúmulo estelar abierto que contiene estrellas calientes
        de tipo espectral B, de mediana edad, ubicadas en la constelación de Tauro. Está entre uno de los cúmulos
        estelares más cercanos a la Tierra, y es el cúmulo mejor visible a simple vista en el cielo nocturno. Las
        Pléyades
        albergan un prominente lugar en la mitología antigua, así como una diversidad de significados en diferentes
        culturas y tradiciones.
        <br><br>
        Mitología
        <br>
        En la mitología griega, las Pléyades (en griego Πλειας Pleias, ‘muchas’; Πλειάδες Pleiades, ‘hijas de Pléyone’; o
        Πελειαδες Peleiades, ‘hijas de palomas’) eran las siete hijas del titán Atlas y la ninfa marina Pléyone, nacidas
        en el monte Cilene. Son hermanas de Calipso, Hiante, las Híades y las Hespérides. Junto con las siete Híades
        eran llamadas Atlántidas, Dodónidas o Nisíadas, niñeras y maestras del infante Dioniso. Las Pléyades eran ninfas 
        en el cortejo de Artemisa, compartían la afición por la caza de ésta, y como ella intentaban mantener su virginidad.
        <br><br>
      </div>


    </div>

    <br><br><br>

  </div>
</center>

{% include 'components/footer.html' %}

Codigo Fuente/web/templates/utils/contactanos.html
{% include 'components/header.html' %}
<center>
    <div class="bg-light m-5 p-5" style="max-width: 1000px;">

        <h2><strong>Contáctanos</strong></h2>

        <br><br><br>

        <div class="text-justify">
            <div class="pr-5 container">

                <div class="row">

                    <div class="col-12" style="width: 50%;">
                        <center>
                            <a class="mt-0" href="http://www.educatic.com.co" target="_blank">
                                <img src="{{url_for('static', filename='images/Educatic_logo.png')}}"
                                    class="d-inline-block align-top" title="www.educatic.com.co">
                            </a>
                            <br>
                            <a href="http://www.educatic.com.co/" target="_blank">Educatic</a><br>
                            <br>
                            Celular: (+57) 311 634 45 26 <br>
                            Dirección: Carrera 42 N° 5 SUR 145, <br>
                            Piso 13, oficina 125, WeWork,<br>
                            Medellín, Antioquia <br>
                            Email: walter.alvarez@educatic.com.co <br>
                            Servicio y Soporte: soporte@educatic.com.co <br>
                            <br><br>
                        </center>
                    </div>


                </div>
            </div>
        </div>
        <br><br>
    </div>
</center>
{% include 'components/footer.html' %}

Codigo Fuente/web/templates/utils/error.html
{% include 'components/header.html' %}

<div class="jumbotron container mt-5 alert alert-danger p-5" style="max-width:45%;" role="alert">
  
  {% if error %}
    <h4 class="alert-heading">{{error[:error.index(':')]}}</h4>
    <br>
    <p>{{ error[error.index(':'):error.index('.')].replace(':', '') }}</p>
    <hr>
    <p class="mb-0">{{ error[error.index('.'):].replace('.', '') }}</p>
  {% else %}

    {% if exception %}
        <h4 class="alert-heading"> ¡ERROR!</h4>
      <p>Ha ocurrido un error en la ejecución del servidor, si es necesario contacte al Administrador del sistema para verificar el error.</p>
      <hr>
    {% else %}

      {% if mensaje %}
        <h4 class="alert-heading">Aviso!!</h4>
        <p>{{mensaje}}</p>
        <hr>
        <p>{{submensaje}}</p>
        {% else %}
        <h4 class="alert-heading">Not Handled Error</h4>
        <p>Please Verify the uncatchable error</p>
      {% endif %}
      
    {% endif %}

  {% endif %}
</div>

{% include 'components/footer.html' %}

Codigo Fuente/web/templates/utils/inicio.html
{% include 'components/header.html' %}
<center>
  <div class="bg-light m-5 p-5" style="max-width: 900px;">

    <h2> <strong> Bienvenido a PLEYADES </strong> </h2>

    {% if session['user'] %}
    {{session['user']['nombre']}}
    {% endif %}

    <br><br><br>

    <div class="mx-5 lead text-justify " style="font-size: 16px;">
      

      La deserción estudiantil de las instituciones de educación superior es un problema que ha afectado de distintas
      formas a todos y preocupa tanto a sus directivos como a las autoridades educativas de la región.
      Actualmente se viene adelantando proyectos que pretenden implementar modelos de predicción de deserción de estudiantil;
      sin embargo, es necesario que estos tipos de proyectos y modelos de predicción se articulén a los procesos de las instituciones 
      para facilitar su ejecución y manejo de la desercion dentro del contexto de cada una.

      <br><br>

      <em>PLEYADES (PLataforma de Exploración Y Analítica para la Deserción EStudiantil)</em> es un sistema de información
      que apoya el análisis del modelo de predicción de deserción estudiantil.

      <br>

      Por medio de Inteligencia Artificial, <em>PLEYADES</em> es capaz de predecir e identificar y analizar
      los posibles desertores entre un conjunto de estudiantes pertenecientes a un programa.

    </div>

    <br><br><br>

    {% if session['user'] %}
    <center><a type="button" class="btn btn-dark text-white my-primary" href="{{url_for('Conjunto.crudos') }}"> Empezar <i class="fa fa-arrow-alt-circle-right ml-1"></i> </a>
    </center>
    {% endif %}

  </div>
</center>

{% include 'components/footer.html' %}

Codigo Fuente/web/templates/utils/login.html
{% include 'components/header.html' %}
<div class="d-flex align-self-stretch bg-light h-100">
    <form action="{{url_for('auth.login')}}" method="POST" data-toggle="validator"
        class="jumbotron container mt-5 py-4 px-5 bg-white border rounded" style="max-width:30%;">
        <center>
            <h4>Iniciar Sesión</h4>
        </center>
        <br>
        <div class="form-group">
            <input type="email" class="form-control" id="InputEmailLoginID" name="InputEmailLogin" aria-describedby="emailHelp"
                placeholder="Dirección de correo" required>

        </div>
        <div class="form-group d-flex align-content-center align-items-center">
            <input type="password" class="form-control mb-1" id="InputPasswordLoginID" name="InputPasswordLogin"
                placeholder="Contraseña" required>
            &nbsp;
        <div class="align-self-center fa fa-eye ml-1" onclick="password()" style="cursor:pointer"></div>
        </div>

        <script>
            function password() {
                var x = document.getElementById("InputPasswordLoginID");
                if (x.type === "password") {
                    x.type = "text";
                } else {
                    x.type = "password";
                }
            }
        </script>

    
        {% if mensaje %}
        <div class="alert alert-danger py-0" role="alert">
            <p class="pt-1">{{mensaje}}</p>
        </div>
        {% endif %}

        <div class="d-flex justify-content-end"><a href="#"><small>¿Olvido su contraseña?</small></a></div>
        <br>

        <div class="text-center">
            <input type="submit" value="Entrar" class="btn btn-dark text-white my-primary" />
        </div>

    </form>
</div>

<script>
    function goBack() {
        window.history.go(-1);
    }
</script>
{% include 'components/footer.html' %}

Codigo Fuente/web/templates/utils/mensaje.html
{% include 'components/header.html' %}

{% include 'components/sideBar.html' %}

  <div class="alert alert-danger w-50" style="max-width: 50%;" role="alert">
    <h5 class="alert-heading">Aviso!!</h5>
    <p>{{mensaje}}</p>
    <hr>

    {% if submensaje is mapping %}

      {% for key, value in submensaje.items() %}
      <p class="mb-2 ml-2"><strong>{{ key }}</strong>:  {{ value }} </p>
      {% endfor %}

    {% else %}
      <p class="mb-2 ml-2">{{submensaje}}</p>
    {% endif %}
  
  </div>
  <!-- <button onclick="goBack()" class="btn btn-outline-dark">Atras</button>


<script>
  function goBack() {
    window.history.go(-1);
  }
</script> -->
{% include 'components/footer.html' %}