Codigo Fuente/web/views/conjuntos.py
from flask import request, session, Blueprint, render_template, redirect, send_file, url_for
from dotenv import load_dotenv
from datetime import datetime
from ast import literal_eval
from googletrans import Translator
import os, sys, json, pandas as pd

from services.db_cli import DB
from utils.modelo import preparar_data, verificar_data, ejecutar_modelo
from views.auth import login_required
from services.API import get, post, put, delete

from utils.utils import *

model_logger = logging.getLogger('model_logger')
error_logger = logging.getLogger('error_logger')

load_dotenv()

Conjunto = Blueprint('Conjunto', __name__)

endopoint = 'conjuntos/'

upload_folder = os.getcwd()+os.getenv("UPLOAD_FOLDER")

translator = Translator()

db = DB()

@Conjunto.route('/crudos')
@login_required
def crudos():
    return listar('crudos')

@Conjunto.route('/procesados')
@login_required
def procesados():
    return listar('procesados')
    
def listar(estado):
    status_p,body_p = get('programas')
    status_c,body_c = get('conjuntos/encargado/'+session['user']['correo']+'?estado='+estado)
    if status_c and status_p:
        return render_template(endopoint+estado+'.html', conjuntos=body_c, programas=body_p)        
    elif not(status_c) and not(status_p):
        error = {**body_c,**body_p}
    elif not(status_c):
        error = body_c
    else:
        error = body_p
    return render_template(endopoint+estado+'.html', conjuntos=[],error=error)

@Conjunto.route('/descargar/<estado>/<nombre>')
def descargar (estado, nombre):

    status_c,body_c = get('conjuntos/'+nombre)
    if not status_c:
        return render_template('utils/mensaje.html', mensaje='No existe ese conjunto')
    
    if estado.lower() == 'crudos':
        nombre = 'C '+nombre
    elif estado.lower() == 'procesados':
        nombre = 'P '+nombre
    else:
        return render_template('utils/mensaje.html', mensaje='Estado del conjunto incorrecto')

    ruta = upload_folder+'/'+estado.lower()+'/'+nombre
    
    if os.path.exists(ruta+'.xlsx'):
        return send_file(ruta+'.xlsx', as_attachment=True)
    elif os.path.exists(ruta+'.xls'):
        return send_file(ruta+'.xls', as_attachment=True)
    else:
        return render_template('utils/mensaje.html', mensaje='No se encontro el archivo a descargar')    
    

@Conjunto.route('/crear')
@login_required
def crear():
    status_f,body_f = get('facultades')
    status_p,body_p = get('programas')

    if status_f and status_p:
        return render_template(endopoint+'crear.html', facultades=body_f, programas=body_p)
    elif not(status_f) and not(status_p):
        error = {**body_f,**body_p}
    elif not(status_f):
        error = body_f
    else:
        error = body_p
    return render_template('utils/mensaje.html', mensaje='No se pudieron cargar las programas y las facultades', submensaje=error)

@Conjunto.route('/detalle',methods=['POST'])
@login_required
def detalle():
    # Obtener Lo valores del formulario
    body = dict(request.values)
    conjunto = literal_eval(body['conjunto'])
    # Consultas para mostrar info
    status_f,body_f = get('facultades')
    status_p,body_p = get('programas')
    status_u, body_u = get('usuarios')
    
    if status_p and status_f and status_u and conjunto:
        return render_template(endopoint+'detalle.html', facultades=body_f, programas=body_p, usuarios=body_u, c=conjunto)
    elif not(status_f) and not(status_p) and not(status_u):
        error = {**body_f,**body_p,**body_u}
    elif not(status_f):
        error = body_f
    elif not(status_p):
        error = body_p
    elif not(conjunto):
        return render_template('utils/mensaje.html', mensaje='No se encontro un conjunto para detallar')
    else:
        error = body_u
    return render_template('utils/mensaje.html', mensaje='No se pudieron cargar los datos para detallar el conjunto', submensaje=error)

@Conjunto.route('/crear', methods=['POST'])
@login_required
def guardar():
    # Obtener Lo valores del formulario
    conjunto = dict(request.values)
    # Preparar conjunto para la insercion
    del conjunto['facultad']
    conjunto['estado'] = 'Crudos'
    conjunto['periodoInicial'] = int(conjunto['periodoInicial'])
    conjunto['periodoFinal'] = int(conjunto['periodoFinal'])
    conjunto['programa'] = int(conjunto['programa'])
    conjunto['encargado'] = session['user']['correo']

    # Obtener nombre del conjunto desde el api
    status_n, body_n = post('conjuntos/nombre', conjunto)
    if status_n:
        nombre, numero = body_n['nombre'], body_n['numero']
    else:
        return render_template('utils/mensaje.html', mensaje='No se pudo obtener el nombre del conjunto', submensaje=body_n)

    archivo_guardar = 'C '+ nombre
    tipo = conjunto['tipo']
    ruta = upload_folder+'/crudos'
    archivo = request.files['archivo']

    # Guardar archivo en Upload folder

    ############# ARCHIVO ##############
    if (archivo.filename and tipo=='excel'):
        extension = '.'+archivo.filename.split('.')[1]
        # Guardar archivo de excel
        archivo_guardar = archivo_guardar + '.xls'
        if not (extension in ['.xls', '.xlsx']):
            return render_template('utils/mensaje.html', mensaje='Extension de archivo incorrecta: '+str(extension), submensaje='Solo se permiten archivos excel .xls & xlsx')
    
        # VERIFICACION de formato
        data = pd.read_excel(archivo)
        validacion, mensaje_error, data_verificada = verificar_data(data, conjunto['periodoInicial'], conjunto['periodoFinal'], conjunto['programa'])
        if validacion:
            try:
                data_verificada.to_excel(ruta+'/'+archivo_guardar, index=False)
                # archivo.save(os.path.join(ruta, nombre + extension))
            except Exception as e:
                error_logger.error(e)
                return render_template('utils/mensaje.html', mensaje='Ocurrio un error guardando el conjunto de datos')
        else:
            return render_template('utils/mensaje.html', mensaje='Incorrecto el formato de la fuente de datos', submensaje=mensaje_error)
    
    ############# CONSULTA ##############
    elif tipo=='consulta':
        # Obtener datos desde la bd SQL server       
        sql = "SELECT * FROM VWDATADESERCION WHERE idprograma={} AND registro >= {} AND registro <= {} "
        sentencia = sql.format(conjunto['programa'], conjunto['periodoInicial'], conjunto['periodoFinal'])
        data = db.select(sentencia)
        ex = exception(data)
        if ex: return ex
        
        # VERIFICACION de formato
        validacion, mensaje_error, data_verificada = verificar_data(data, conjunto['periodoInicial'], conjunto['periodoFinal'], conjunto['programa'])
        if validacion:
            # Guardar tabla sql como excel
            try:
                data_verificada.to_excel(ruta+'/'+archivo_guardar+'.xls', index=False)
            except Exception as e:
                error_logger.error(e)
                return render_template('utils/mensaje.html', mensaje='Ocurrio un error guardando el conjunto de datos')
        else:
            return render_template('utils/mensaje.html', mensaje='Incorrecto el formato de la fuente de datos', submensaje=mensaje_error)
    else:
        return render_template('utils/mensaje.html', mensaje='Formulario incorrecto', submensaje='Verifica el formulario de creacion o notifica al Administrador del sistema')
           
    # Guardar registro de conjunto en la BD
    conjunto['nombre'] =  nombre
    conjunto['numero'] =  numero
    status, body = post('conjuntos',conjunto)
    if status:
        return redirect(url_for('Conjunto.crudos'))
    else:
        return render_template('utils/mensaje.html', mensaje='No se pudo guardar el conjunto', submensaje=body)


@Conjunto.route('/preparar', methods=['POST'])
@login_required
def preparar():
    # Obtener Lo valores del formulario
    body = dict(request.values)
    conjunto = literal_eval(body['conjunto'])
    
    nombre = conjunto['nombre']

    # Actualizar conjunto de datos de crudo a en proceso 
    act_estado =  actualizar_estado(nombre,'En Proceso')
    if act_estado: return act_estado

    # Crear prepraracion
    preparacion = {}
    preparacion['conjunto'] = conjunto['nombre']
    preparacion['preparador'] = session['user']['correo']
    preparacion['fechaInicial'] = getNowDate()
    # Obtener numero de preparacion para el conjunto
    status_p, body_p = get('preparaciones/nombre/'+nombre)
    if status_p:
        preparacion['numero'] = body_p['numero']
        preparacion['nombre'] = body_p['nombre']
    else:
        return render_template('utils/mensaje.html', mensaje='No se pudo obtener el consecutivo de la preparacion para este conjunto', submensaje=body_p)

    ########### PREPARAR ############

    # Obtener archivo crudo
    archivo_crudo = 'C '+nombre 
    ruta = upload_folder+'/crudos/'+archivo_crudo
    exito,dataCruda = obtener_archivo_excel(ruta) 
    if not(exito): return dataCruda 

    # Algoritmo de preparacion
    try:
        dataPreparada = preparar_data(dataCruda)
    except Exception as e:
        model_logger.error(e)
        observaciones = {'error': str(e)}
        exito,pagina_error = guardar_preparacion(preparacion, observaciones,'Fallida')
        if not(exito): return pagina_error 
        return render_template('utils/mensaje.html', mensaje='La preparacion Fallo')

    # Guardar archivo en Upload folder procesados
    archivo_procesado = 'P '+nombre+'.xls'
    ruta = upload_folder+'/procesados/'+archivo_procesado
    exito,pagina_error = guardar_archivo(dataPreparada, ruta, 'excel')
    if not(exito): return pagina_error 

    # Guardar registro de preparacion en la BD 
    exito, pagina_error = guardar_preparacion(preparacion,None,'Exitosa')
    if not(exito): return pagina_error 

    ########### FIN PREPARAR ############    

    # Actualizar conjunto de datos de crudo a procesado
    act_estado =  actualizar_estado(nombre,'Procesados')

Codigo Fuente/web/views/resultados.py
from flask import request, session, Blueprint, render_template, redirect, send_file
from dotenv import load_dotenv
from ast import literal_eval
from datetime import datetime
import os, json, pandas as pd

from views.auth import login_required
from services.API import get, post, put, delete

from utils.utils import *

load_dotenv()

endopoint = 'resultados/'

Resultado = Blueprint('Resultado', __name__)

upload_folder = os.getcwd()+os.getenv("UPLOAD_FOLDER")

@Resultado.route('/preparaciones')
@Resultado.route('/preparaciones/<conjunto>')
@login_required
def preparaciones(conjunto=None):
    if conjunto:
        return listar_conjunto('preparaciones', conjunto)
    return listar('preparaciones')

@Resultado.route('/ejecuciones')
@Resultado.route('/ejecuciones/<conjunto>')
@login_required
def ejecuciones(conjunto=None):
    if conjunto:
        return listar_conjunto('ejecuciones',conjunto)
    return listar('ejecuciones')

def listar(resultados):
    rol = 'preparador' if resultados == 'preparaciones' else 'ejecutor'
    status, body = get(resultados+'/'+rol+'/'+session['user']['correo'])
    if status:
        return render_template(endopoint+resultados+'.html', resultados=set_date_format(body))
    else:
        return render_template(endopoint+resultados+'.html', resultados=[], error=body)

def listar_conjunto(resultados, conjunto):
    status, body = get(resultados+'/conjunto/'+conjunto)
    if status:
        return render_template(endopoint+resultados+'.html', resultados=set_date_format(body))
    else:
        return render_template(endopoint+resultados+'.html', resultados=[], error=body)


@Resultado.route('/ejecucion/detalle', methods=['POST'])
@login_required
def ejecucion_detalle():
    body = dict(request.values)
    ejecucion = body['ejecucion']

    # Obtener el archivo de desertores
    archivo = 'D '+ejecucion
    ruta = upload_folder+'/desertores/'+archivo
    exito,desertores = obtener_archivo_json(ruta)

    status, body = get('ejecuciones/'+ejecucion)
 
    if status and exito:
        del body['precision_modelo']
        del body['numero']
        return render_template(endopoint+'ejecucion_detalle.html', desertores=desertores, resultados=body.pop('resultados'), ejecucion=body )
    elif status and not(exito):
        if body['estado'] == 'Fallida':
            del body['precision_modelo']
            del body['numero']
            return render_template(endopoint+'ejecucion_detalle.html', desertores=None, resultados=body.pop('resultados'), ejecucion=body )
        else:
            return desertores
    else:
        return render_template('utils/mensaje.html', mensaje='No se obtener la ejecucion', submensaje=body)

@Resultado.route('/preparacion/detalle', methods=['POST'])
@login_required
def preparacion_detalle():
    body = dict(request.values)
    preparacion = body['preparacion']
    status, body = get('preparaciones/'+preparacion)
    
    if status:
        del body['numero']
        return render_template(endopoint+'preparacion_detalle.html', observaciones=body.pop('observaciones') ,p=body )
    else:
        return render_template('utils/mensaje.html', mensaje='No se obtener los resultaods de la ejecucion', submensaje=body)


@Resultado.route('/descargar/desertores/<ejecucion>', methods=['GET'])
@login_required
def descargar(ejecucion):
    status_c,body_c = get('ejecuciones/'+ejecucion)
    if not status_c:
        return render_template('utils/mensaje.html', mensaje='No existe esa ejecucion')

    archivo = 'D '+ejecucion
    ruta = upload_folder+'/desertores/'+archivo
    try:
        data = pd.read_json(ruta+'.json')
    except Exception as e:
        return render_template('utils/mensaje.html', mensaje='No se pudo abrir el archivo de desertores:', submensaje=str(e))
    
    exito,pagina_error = guardar_archivo(data,ruta+'.xls','excel')
    if not(exito): return pagina_error 

    return send_file(ruta+'.xls', as_attachment=True)

Codigo Fuente/web/templates/resultados/ejecucion_detalle.html
{% include 'components/header.html' %}

{% with menu='resultados' %}
    {% include 'components/sideBar.html' %}
{% endwith %}

<h4>Detalles de una Ejecucion</h4>
<br>



<div class="container border rounded pt-3 pl-5 float-left">

  <div class="row">
    {% if desertores %}
    <div class="col">
      <h5 class="mb-3 font-weight-bold ">Desertores</h5>
      <div class="d-flex ml-1 mt-2">
        &nbsp;<i class="fas fa-filter mr-2 mt-2""></i>&nbsp;
        <input type=" text" class="form-control form-control-sm" id="filtro_tabla" placeholder="Filtrar tabla...">
      </div>
      <br>
      <div class="table-responsive-sm">
        <table class="table table-hover table-sm" id="tabla">
          <thead>
            <tr>
              <th scope="col" class="font-weight-normal">
                <center> Documento de Identificación </center>
              </th>
              <th scope="col" class="font-weight-normal">
                <center> Nombre </center>
              </th>
              <!-- <th scope="col" class="font-weight-normal">
                  <center> Desertor </center>
                </th> -->
              <th scope="col" class="font-weight-normal">
                <center> Prediccion </center>
              </th>
            </tr>
          </thead>
          <tbody class="bg-light rounded">
            {% for d in desertores %}
            <tr>
              <td>
                <center>{{ d.documento }}</center>
              </td>
              <td>{{ d.nombre_completo }}</td>
              <td>
                <center>
                  {% if d.desertor==0 %}

                  <i class="fas fa-exclamation-circle fa-lg text-warning border-dark" data-toggle="tooltip"
                    data-placement="bottom" style="cursor: pointer;"
                    title="El modelo predijo que este estudiante&#10;podria ser un potencial desertor,&#10;aunque no ha sido reportado como tal."></i>
                  {% else %}
                  <i class="fas fa-check-circle text-secondary" data-toggle="tooltip" data-placement="bottom"
                    style="cursor: pointer;"
                    title="El modelo y el reporte coincidio definiendo este estudiante como desertor."></i>
                  {% endif %}
                </center>
              </td>
              <!-- <td>{{ d.prediccion }}</td> -->
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    {% endif %}

    <div class="col ml-5">
      <h5 class="mb-3 font-weight-bold">Resultados</h5>
      <br>
      <table class="table table-bordered w-75 ml-3" style="max-width: 70%;">
        <tbody>
          {% for key, value in resultados.items() %}
          <tr>
            <td><strong>{{ key.title()|replace('_',' ') }}</strong></td>
            <td class="bg-light">
              {{ value }}
              {% if key=='precision' %}
              %
              {% endif %}
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
      
      {% if desertores %}
      <div class="d-flex justify-content-center align-items-center  ml-0 pl-0 mr-5 pr-5">
        <i class="fa fa-download" aria-hidden="true"></i>
        &nbsp;
        <div class="ml-0 pl-0 mr-2 d-flex ">Descargar: </div>
        &nbsp;&nbsp;
        <a class="btn bg-light btn-sm border text-dark px-2" type=" button"
          href="{{url_for('Resultado.descargar',ejecucion=ejecucion.nombre)}}">
          <i class="fas fa-file-excel mr-1" aria-hidden="true"></i>
          Desertores
        </a>
      </div>
      
      <br><br><br>
      {% endif %}
      <br>
      <div class="col">
        <h5 class="mb-3 font-weight-bold ">Detalle</h5>
        
        <table class="table table-bordered w-75">
          <tbody>
            {% for key, value in ejecucion.items() %}
            <tr>
              <td><strong>{{ key.title()|replace('_',' ') }}</strong></td>
              <td class="bg-light">
                {{ value }}
                {% if key=='duracion' %}
                seg
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>



      <br><br><br>
      <div class="text-center ml-0 pl-0 mr-5 pr-5">
        <a class="btn btn-outline-dark ml-0 mr-3" href="{{url_for('Resultado.ejecuciones')}}">Atras</a>
      </div>
      <br>


    </div>

  </div>


</div>




{% include 'components/footer.html' %}

Codigo Fuente/web/templates/resultados/ejecuciones.html
{% include 'components/header.html' %}

{% with menu='resultados' %}
    {% include 'components/sideBar.html' %}
{% endwith %}

<h4>Resultados</h4>
<br>

<!-- Input de filtrado -->
<div class="row ml-1 mt-2">
  &nbsp;<i class="fas fa-filter mr-2 mt-2""></i>&nbsp;
  <input type=" text" class="form-control form-control-sm w-25" id="filtro_tabla" placeholder="Filtrar tabla...">
</div>
<br>

<ul class="nav nav-tabs mb-4">
  <li class="nav-item">
    <a class="nav-link text-dark  bg-light border" href="{{url_for('Resultado.preparaciones')}}">Preparaciones</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active text-dark" href="#">Ejecuciones</a>
  </li>
</ul>
<div class="table-responsive-sm">
  <table class="table table-hover table-sm" id="tabla">
    <thead>
      <tr>
        <th scope="col" class="border-top-0">
          <center>Ejecucion</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Fecha</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Duracion</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Estado</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Acciones</center>
        </th>
      </tr>
    </thead>
    <tbody>
      {% for e in resultados %}
      <tr>
        <td>
          <center>{{ e.nombre }}</center>
        </td>
        <td>
          <center>{{ e.fechaInicial }}</center>
        </td>
        <td>
          <center>{{  '{:.2f}'.format(e.duracion/60)  }} &nbsp;min</center>
        </td>
        <td>
          <center>{{ e.estado }} </center>
        </td>
        <td>
          <center>
            <!--Ver Ejecuciones -->
            <form action="{{url_for('Resultado.ejecucion_detalle')}}" method="POST">
              <input type="hidden" name="ejecucion" value="{{e.nombre}}">
              <button type="submit" data-toggle="tooltip" data-placement="bottom" title="Ver Detalle"
                class="btn btn-outline-dark btn-sm submit" role="status">
                <i class="fas fa-search-plus"></i>
              </button>
            </form>
          </center>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<br>

{% if error %}
{% with titulo='No se pudieron cargar los resultados',error=error %}
{% include "components/alert.html" %}
{% endwith %}
{% endif %}


{% include 'components/footer.html' %}

Codigo Fuente/web/templates/resultados/preparacion_detalle.html
{% include 'components/header.html' %}

{% with menu='resultados' %}
    {% include 'components/sideBar.html' %}
{% endwith %}

<h4>Detalles de una Preparacion</h4>
<br>

{% if observaciones %}
<div class="container pt-3 pl-5 float-left border rounded ">
  {% else %}
  <div class="container pt-3 pl-5 float-left">
    {% endif %}


    <div class="row">

      <div class="col">
        {% if observaciones %}
        <h5 class="mb-3 font-weight-bold ">Detalle</h5>
        {% endif %}

        <table class="table table-bordered w-75">
          <tbody>
            {% for key, value in p.items() %}
            <tr>
              <td><strong>{{ key.title() }}</strong></td>
              <td class="bg-light">

                {{ value }}

                {% if key=='duracion' %}
                seg
                {% endif %}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

        <br>

        <div class="col-sm-11 d-flex justify-content-center align-items-center">
          <i class="fa fa-download" aria-hidden="true"></i>
          &nbsp;
          <strong class="mr-2 d-flex ">Descargar: </strong>
          &nbsp;&nbsp;
          <a class="btn bg-white btn-sm border text-dark" type="button"
            href="{{url_for('Conjunto.descargar',estado='procesados',nombre=p.conjunto)}}">
            <i class="fas fa-file-excel mr-1"></i>
            Procesado
          </a>
        </div>


        <br><br>

        {% if not observaciones %}
        <div class="text-center ml-0 pl-0 mr-5 pr-5">
          <a class="btn btn-outline-dark ml-0 mr-3" href="{{url_for('Resultado.preparaciones')}}">Atras</a>
        </div>
        {% endif %}

        <br>

      </div>

      {% if observaciones %}
      {% if observaciones  is mapping  %}
      <div class="col">
        <h5 class="mb-3 font-weight-bold ">Observaciones</h5>

        <table class="table table-bordered w-75">
          <tbody>
            {% for key, value in observaciones.items() %}
            <tr>
              <td><strong>{{ key.title() }}</strong></td>
              <td class="bg-light">
                {{ value }}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>

      </div>
      {% endif %}
      {% endif %}


    </div>
    {% if observaciones %}
    <div class="row">
      <div class="col">
        <center>
          <a class="btn btn-outline-dark ml-0 mr-3" href="{{url_for('Resultado.preparaciones')}}">Atras</a>
        </center>
      </div>
    </div>
    <br>
    {% endif %}
  </div>




  {% include 'components/footer.html' %}

Codigo Fuente/web/templates/resultados/preparaciones.html
{% include 'components/header.html' %}

{% with menu='resultados' %}
    {% include 'components/sideBar.html' %}
{% endwith %}

<h4>Resultados</h4>
<br>

<!-- Input de filtrado -->
<div class="row ml-1 mt-2">
  &nbsp;<i class="fas fa-filter mr-2 mt-2""></i>&nbsp;
  <input type=" text" class="form-control form-control-sm w-25" id="filtro_tabla" placeholder="Filtrar tabla...">
</div>
<br>

<ul class="nav nav-tabs mb-4">
  <li class="nav-item">
    <a class="nav-link active" href="#">Preparaciones</a>
  </li>
  <li class="nav-item">
    <a class="nav-link text-dark bg-light border" href="{{url_for('Resultado.ejecuciones')}}">Ejecuciones</a>
  </li>
</ul>
<div class="table-responsive-sm">
  <table class="table table-hover table-sm" id="tabla">
    <thead>
      <tr>
        <th scope="col" class="border-top-0">
          <center>Preparacion</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Fecha</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Duracion</center>
        </th>
        <th scope="col" class="border-top-0">
          <center>Estado</center>
        </th>
        <th scope="col" class="border-top-0">
          <center> Acciones</center>
        </th>
      </tr>
    </thead>
    <tbody>
      {% for p in resultados %}
      <tr>
        <td>
          <center>{{ p.nombre }}</center>
        </td>
        <td>
          <center>{{ p.fechaInicial }}</center>
        </td>
        <td>
          <center>{{ p.duracion }} seg</center>
        </td>
        <td>
          <center>{{ p.estado }}</center>
        </td>
        <td>
          <!-- ACCCIONES -->
          <center>
            <div class="btn-group" role="group" aria-label="Basic example">
              <form action="{{url_for('Resultado.preparacion_detalle')}}" method="POST">
                <input type="hidden" name="preparacion" value="{{p.nombre}}">
                <button type="submit" data-toggle="tooltip" data-placement="bottom" title="Ver Detalle"
                  class="btn btn-outline-dark btn-sm submit" role="status">
                  <i class="fas fa-search-plus"></i>
                </button>
              </form>
            </div>
          </center>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>

<br>

{% if error %}
{% with titulo='No se pudieron cargar los resultados',error=error %}
{% include "components/alert.html" %}
{% endwith %}
{% endif %}


{% include 'components/footer.html' %}